//Joke privacy policy text const

export const PRIVACY_POLICY = {
  TITLE: "Privacy Policy",
  SECTION_ONE:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  SECTION_TWO_TITLE: "1. Introduction",
  SECTION_TWO:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  SECTION_THREE_TITLE: "2. Identifying Purposes",
  SECTION_THREE:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  SECTION_FOUR_TITLE: "3. Consent",
  SECTION_FOUR:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  SECTION_FIVE_TITLE: "4. Limiting Collection",
  SECTION_FIVE:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  SECTION_SIX_TITLE: "5. Limiting Use, Disclosure and Retention",
  SECTION_SIX:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  SECTION_SEVEN_TITLE: "6. Accuracy",
  SECTION_SEVEN: "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  SECTION_EIGHT_TITLE_THE_VIDEO_GAME: "7. Safeguarding Customer Information",
  SECTION_EIGHT_THE_VIDEO_GAME:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  DISTRICT_NINE_TITLE: "8. Openness",
  DISTRICT_NINE:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  SECTION_TEN_TITLE: "9. Customer Access",
  SECTION_TEN:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  SEVEN_ELEVEN_TITLE: "10. Handling Customer Complaints and Suggestions",
  SEVEN_ELEVEN:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  ADDITIONAL_INFORMATION: "Additional Information",
  COOKIES_TITLE: "Cookies",
  COOKIE_ONE:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  COOKIE_TWO:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
  OTHER_TITLE: "Other Websites",
  OTHER:
    "THIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKETHIS IS A JOKE",
};
