import {
  ArticleSection,
  FAQLi,
  HomePageH1,
  StyledH2,
  WhiteP,
} from "../components/StyledComponents";
import { PRIVACY_POLICY } from "./PageFiles/PrivacyPolicyTextConsts";

export const PrivacyPolicy = () => {
  return (
    <ArticleSection>
      <HomePageH1>{PRIVACY_POLICY.TITLE}</HomePageH1>
      <WhiteP>{PRIVACY_POLICY.SECTION_ONE}</WhiteP>
      <FAQLi>{PRIVACY_POLICY.SECTION_TWO_TITLE}</FAQLi>
      <WhiteP>{PRIVACY_POLICY.SECTION_TWO}</WhiteP>
      <FAQLi>{PRIVACY_POLICY.SECTION_THREE_TITLE}</FAQLi>
      <WhiteP>{PRIVACY_POLICY.SECTION_THREE}</WhiteP>
      <FAQLi>{PRIVACY_POLICY.SECTION_FOUR_TITLE}</FAQLi>
      <WhiteP>{PRIVACY_POLICY.SECTION_FOUR}</WhiteP>
      <FAQLi>{PRIVACY_POLICY.SECTION_FIVE_TITLE}</FAQLi>
      <WhiteP>{PRIVACY_POLICY.SECTION_FIVE}</WhiteP>
      <FAQLi>{PRIVACY_POLICY.SECTION_SIX_TITLE}</FAQLi>
      <WhiteP>{PRIVACY_POLICY.SECTION_SIX}</WhiteP>
      <FAQLi>{PRIVACY_POLICY.SECTION_SEVEN_TITLE}</FAQLi>
      <WhiteP>{PRIVACY_POLICY.SECTION_SEVEN}</WhiteP>
      <FAQLi> {PRIVACY_POLICY.SECTION_EIGHT_TITLE_THE_VIDEO_GAME}</FAQLi>
      <WhiteP>{PRIVACY_POLICY.SECTION_EIGHT_THE_VIDEO_GAME}</WhiteP>
      <FAQLi>{PRIVACY_POLICY.DISTRICT_NINE_TITLE}</FAQLi>
      <WhiteP>{PRIVACY_POLICY.DISTRICT_NINE}</WhiteP>
      <FAQLi>{PRIVACY_POLICY.SECTION_TEN_TITLE}</FAQLi>
      <WhiteP>{PRIVACY_POLICY.SECTION_TEN}</WhiteP>
      <FAQLi>{PRIVACY_POLICY.SEVEN_ELEVEN_TITLE}</FAQLi>
      <WhiteP>{PRIVACY_POLICY.SEVEN_ELEVEN}</WhiteP>
      <StyledH2 privacy>{PRIVACY_POLICY.ADDITIONAL_INFORMATION}</StyledH2>
      <FAQLi>{PRIVACY_POLICY.COOKIES_TITLE}</FAQLi>
      <WhiteP>{PRIVACY_POLICY.COOKIE_ONE}</WhiteP>
      <WhiteP>{PRIVACY_POLICY.COOKIE_TWO}</WhiteP>
      <FAQLi>{PRIVACY_POLICY.OTHER_TITLE}</FAQLi>
      <WhiteP>{PRIVACY_POLICY.OTHER}</WhiteP>
    </ArticleSection>
  );
};
